# Copyright (c) 2025 nautilus_quants
# SPDX-License-Identifier: MIT
"""
RegimeCompositeActor - Regime-aware dynamic factor composite.

Loads a pre-computed regime_config.yaml (from ``alpha regime`` command)
containing signed weights and a regime schedule. On each bar, looks up
the current regime via bisect and reweights factors accordingly.

Data flow:
    FactorEngineActor → FactorValues (individual factors)
        ↓
    RegimeCompositeActor → FactorValues (regime-aware composite) ← BTC bars
        ↓
    DecisionEngineActor → RebalanceOrders

Constitution Compliance:
    - Extends Nautilus Actor base class (Principle I)
    - Configuration-driven via ActorConfig (Principle II)
    - Pure reweighting, no order submission (Principle V)
"""

from __future__ import annotations

import bisect
import logging
from pathlib import Path

import numpy as np
import pandas as pd
import yaml
from nautilus_trader.common.actor import Actor
from nautilus_trader.common.config import ActorConfig
from nautilus_trader.model.data import Bar, DataType
from nautilus_trader.model.identifiers import ClientId

from nautilus_quants.common.bar_subscription import BarSubscriptionMixin
from nautilus_quants.factors.factor_values import FactorValues

logger = logging.getLogger(__name__)


class RegimeCompositeActorConfig(ActorConfig, frozen=True):
    """Configuration for RegimeCompositeActor.

    Parameters
    ----------
    regime_config_path : str
        Path to regime_config.yaml (generated by ``alpha regime``).
    regime_method : str
        Which method section to use: "jump_model" or "ema".
    composite_name : str
        Name of the output composite factor.
    bar_types : list[str]
        Bar types to subscribe (injected by backtest CLI).
    """

    regime_config_path: str = ""
    regime_method: str = "ema"
    composite_name: str = "composite"
    bar_types: list[str] = []


class RegimeCompositeActor(BarSubscriptionMixin, Actor):
    """Regime-aware dynamic factor composite actor.

    Loads regime schedule + signed weights from regime_config.yaml.
    On each bar, bisect-lookups the current regime and publishes a
    weighted composite factor.
    """

    def __init__(self, config: RegimeCompositeActorConfig) -> None:
        super().__init__(config)
        self._composite_name = config.composite_name

        # Loaded from regime_config.yaml in on_start()
        self._regime_instrument: str = ""
        self._factor_names: list[str] = []
        self._weight_map: dict[str, dict[str, float]] = {}
        self._schedule_ns: list[int] = []
        self._schedule_regimes: list[str] = []
        self._current_regime: str = ""

        self._pending_factors: dict[str, dict[str, float]] | None = None
        self._bar_count: int = 0
        self._publishing: bool = False

    def on_start(self) -> None:
        self._load_regime_config()
        self._subscribe_bar_types(self.config.bar_types)
        self.subscribe_data(DataType(FactorValues), client_id=ClientId(self.id.value))
        self.log.info(
            f"RegimeCompositeActor started: "
            f"method={self.config.regime_method}, "
            f"regime_instrument={self._regime_instrument}, "
            f"factors={len(self._factor_names)}, "
            f"regimes={list(self._weight_map.keys())}, "
            f"schedule_transitions={len(self._schedule_ns)}",
        )

    def _load_regime_config(self) -> None:
        """Load weights + schedule from regime_config.yaml."""
        path = Path(self.config.regime_config_path)
        if not path.exists():
            raise FileNotFoundError(
                f"regime_config not found: {path}"
            )

        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f)

        # Metadata
        metadata = data.get("metadata", {})
        self._regime_instrument = metadata.get(
            "regime_instrument", "BTCUSDT.BINANCE",
        )

        # Method section
        method = self.config.regime_method
        section = data.get(method)
        if section is None:
            raise ValueError(
                f"Method '{method}' not found in {path}. "
                f"Available: {[k for k in data if k != 'metadata']}"
            )

        # Weights (signed)
        self._weight_map = dict(section["weights"])

        # Default weights from factor config composite (pre-schedule fallback)
        default_w = metadata.get("default_weights", {})
        if default_w:
            self._weight_map["_default"] = default_w

        # Derive factor names from weights keys (any regime)
        first_regime = next(iter(section["weights"].values()))
        self._factor_names = list(first_regime.keys())

        # Schedule: ISO string → nanosecond int
        schedule_raw = section.get("schedule", {})
        schedule_pairs = sorted(
            (pd.Timestamp(ts).value, regime)
            for ts, regime in schedule_raw.items()
        )
        self._schedule_ns = [t for t, _ in schedule_pairs]
        self._schedule_regimes = [r for _, r in schedule_pairs]

        # Initialize current regime
        if self._schedule_regimes:
            self._current_regime = self._schedule_regimes[0]

    def on_bar(self, bar: Bar) -> None:
        instrument_id = str(bar.bar_type.instrument_id)
        if instrument_id != self._regime_instrument:
            return

        # Bisect lookup: O(log n) where n = number of transitions
        idx = bisect.bisect_right(
            self._schedule_ns, bar.ts_event,
        ) - 1
        prev_regime = self._current_regime
        if idx >= 0:
            self._current_regime = self._schedule_regimes[idx]
        else:
            # Before first schedule entry: fallback uses factor config
            # composite weights (equal/static from factors YAML)
            self._current_regime = "_default"

        if self._current_regime != prev_regime:
            self.log.info(
                f"Regime switch: {prev_regime} → {self._current_regime} "
                f"at bar_count={self._bar_count}",
            )

        self._bar_count += 1
        self._try_publish()

    def on_data(self, data: FactorValues) -> None:
        if not isinstance(data, FactorValues):
            return
        if self._publishing:
            return
        self._pending_factors = data.factors
        self._try_publish()

    def _try_publish(self) -> None:
        """Publish regime-aware composite if both bar and factors available."""
        if self._pending_factors is None or not self._current_regime:
            return

        factors = self._pending_factors
        self._pending_factors = None

        # Select signed weights for current regime
        weights = self._weight_map.get(self._current_regime)
        if weights is None:
            n = len(self._factor_names)
            weights = {name: 1.0 / n for name in self._factor_names}

        # Collect factor arrays
        factor_arrays: dict[str, dict[str, float]] = {}
        for name in self._factor_names:
            if name in factors:
                factor_arrays[name] = factors[name]

        if not factor_arrays:
            if self._bar_count <= 3:
                self.log.warning(
                    f"No matching factors in data. "
                    f"Expected: {self._factor_names[:3]}... "
                    f"Got: {list(factors.keys())[:5]}...",
                )
            return

        # All instruments
        all_instruments: set[str] = set()
        for vals in factor_arrays.values():
            all_instruments.update(vals.keys())

        # Cross-sectional normalize per factor
        normalized: dict[str, dict[str, float]] = {}
        for name, vals in factor_arrays.items():
            values = np.array(
                [vals.get(inst, np.nan) for inst in all_instruments],
            )
            valid = ~np.isnan(values)
            if valid.sum() < 2:
                continue
            mean = np.nanmean(values)
            std = np.nanstd(values)
            if std < 1e-12:
                continue
            norm_values = (values - mean) / std
            normalized[name] = {
                inst: float(nv)
                for inst, nv, v in zip(all_instruments, norm_values, valid)
                if v
            }

        # Signed weighted composite, normalized by sum(abs(w))
        composite: dict[str, float] = {}
        for inst in all_instruments:
            total = 0.0
            total_abs_weight = 0.0
            for name in self._factor_names:
                if name in normalized and inst in normalized[name]:
                    w = weights.get(name, 0.0)
                    total += w * normalized[name][inst]
                    total_abs_weight += abs(w)
            if total_abs_weight > 0:
                composite[inst] = total / total_abs_weight

        if not composite:
            return

        output_factors = dict(factors)
        output_factors[self._composite_name] = composite

        fv = FactorValues.create(
            ts_event=self.clock.timestamp_ns(),
            factors=output_factors,
        )
        self._publishing = True
        self.publish_data(data_type=DataType(FactorValues), data=fv)
        self._publishing = False

        if self._bar_count % 200 == 0 or self._bar_count <= 3:
            self.log.info(
                f"Published {self._composite_name}: "
                f"regime={self._current_regime}, "
                f"instruments={len(composite)}, "
                f"bar={self._bar_count}, "
                f"factor_count={len(factor_arrays)}",
            )

    def on_stop(self) -> None:
        self.log.info(
            f"RegimeCompositeActor stopped. "
            f"Total bars={self._bar_count}, "
            f"final_regime={self._current_regime}",
        )
