# Copyright (c) 2025 nautilus_quants
# SPDX-License-Identifier: MIT
"""Export factor registry to a standard factors.yaml (round-trip safe)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from nautilus_quants.alpha.registry.models import FactorRecord
from nautilus_quants.alpha.registry.repository import FactorRepository


def export_factors_yaml(
    repo: FactorRepository,
    output_path: Path,
    context_id: str = "",
    status: str = "active",
    composite_method: str = "equal",
    composite_top_n: int = 30,
    composite_transform: str = "cs_rank",
) -> Path:
    """Generate a complete ``factors.yaml`` from the registry.

    The output is directly loadable by ``load_factor_config()``.
    """
    # 1. Query factors, sorted by promote_score desc (then top_n slice)
    factors = repo.list_factors(status=status)
    factors.sort(
        key=lambda f: f.parameters.get("promote_score", 0) if f.parameters else 0,
        reverse=True,
    )
    factors = factors[:composite_top_n]

    # 2. Load config snapshot for variables/parameters if context_id given
    variables: dict[str, str] = {}
    parameters: dict[str, Any] = {}
    source = ""
    if context_id:
        snap = repo.get_config_snapshot(context_id)
        if snap is not None:
            cj = snap.config_json
            variables = cj.get("variables", {})
            parameters = cj.get("parameters", {})
            source = cj.get("metadata", {}).get("source", "")

    # If no snapshot, derive variables/parameters from first factor
    if not variables and factors:
        variables = factors[0].variables
    if not parameters and factors:
        parameters = {
            k: v for k, v in (factors[0].parameters or {}).items()
            if k != "promote_score"
        }
    if not source and factors:
        source = factors[0].source

    # 3. Compute weights
    weights = _compute_weights(factors, composite_method, repo)

    # 4. Build composite expression
    composite_expr = _build_composite_expression(weights, composite_transform)

    # 5. Assemble YAML
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    doc: dict[str, Any] = {}

    doc["metadata"] = {
        "name": f"registry_export{'_' + context_id if context_id else ''}",
        "source": source,
        "version": "1.0.0",
        "description": (
            f"Auto-generated from registry ({len(factors)} {status} factors, "
            f"method={composite_method}, transform={composite_transform})"
        ),
    }

    if parameters:
        doc["parameters"] = parameters
    if variables:
        doc["variables"] = variables

    factors_section: dict[str, dict[str, Any]] = {}
    for f in factors:
        entry: dict[str, Any] = {"expression": f.expression}
        if f.description:
            entry["description"] = f.description
        if f.tags:
            entry["tags"] = f.tags
        if f.prototype:
            entry["prototype"] = f.prototype
        # Strip source prefix so re-import won't double-prefix
        key = f.factor_id
        if source and key.startswith(f"{source}_"):
            key = key[len(source) + 1:]
        factors_section[key] = entry
    doc["factors"] = factors_section

    # Declarative composite section
    if weights:
        doc["composite"] = {
            "name": "composite",
            "transform": composite_transform,
            "weights": {fid: round(w, 4) for fid, w in weights},
        }

    # 6. Write YAML
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        f"# Auto-generated by alpha export-factors\n"
        f"# method: {composite_method}, top: {composite_top_n}, "
        f"transform: {composite_transform}\n"
        f"# generated: {now}\n\n"
    )

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(header)
        yaml.dump(
            doc, fh, default_flow_style=False,
            allow_unicode=True, sort_keys=False,
        )

    return output_path


def _compute_weights(
    factors: list[FactorRecord],
    method: str,
    repo: FactorRepository | None = None,
) -> list[tuple[str, float]]:
    """Compute factor weights as (factor_id, weight) pairs."""
    if not factors:
        return []

    if method == "icir_weight" and repo is not None:
        # Get latest ICIR from analysis metrics
        icir_values: list[tuple[str, float]] = []
        for f in factors:
            metrics = repo.get_metrics(f.factor_id)
            if metrics:
                best = max(
                    (m for m in metrics if m.icir is not None),
                    key=lambda m: abs(m.icir or 0),
                    default=None,
                )
                if best and best.icir is not None:
                    icir_values.append((f.factor_id, abs(best.icir)))
        if icir_values:
            total = sum(v for _, v in icir_values)
            if total > 0:
                return [(fid, v / total) for fid, v in icir_values]

    # Default: equal weight
    n = len(factors)
    w = 1.0 / n
    return [(f.factor_id, w) for f in factors]


def _build_composite_expression(
    weights: list[tuple[str, float]],
    transform: str,
) -> str:
    """Build a DSL expression from weights and transform."""
    if not weights:
        return "0"

    terms: list[str] = []
    for factor_id, weight in weights:
        if transform == "raw":
            term = f"{weight:.4f} * {factor_id}"
        else:
            term = f"{weight:.4f} * {transform}({factor_id})"
        terms.append(term)

    return "\n+ ".join(terms)
