# Copyright (c) 2025 nautilus_quants
# SPDX-License-Identifier: MIT
"""Export factor registry to a standard factors.yaml (round-trip safe)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from nautilus_quants.alpha.registry.models import FactorRecord
from nautilus_quants.alpha.registry.repository import FactorRepository


def export_factors_yaml(
    repo: FactorRepository,
    output_path: Path,
    status: str = "active",
    composite_method: str = "equal",
    composite_top_n: int = 30,
    composite_transform: str = "cs_rank",
) -> Path:
    """Generate a complete ``factors.yaml`` from the registry.

    The output is directly loadable by ``load_factor_config()``.
    Variables and parameters are auto-resolved from the ``context_id``
    stored on each factor (set during ``alpha register``).

    Parameters
    ----------
    repo : FactorRepository
        Repository to query.
    output_path : Path
        Destination YAML path.
    status : str
        Filter factors by this status (default "active").
    composite_method : str
        Weighting method: "equal" or "icir_weight".
    composite_top_n : int
        Maximum number of factors in the composite.
    composite_transform : str
        Transform applied to each factor in the composite expression:
        "cs_rank", "cs_zscore", or "raw".

    Returns
    -------
    Path
        The output path.
    """
    # 1. Query factors (exclude any existing "composite" to avoid overwriting
    #    a user-defined composite expression; sort by |ICIR| descending so
    #    top-N selects the strongest-signal factors regardless of sign).
    factors = repo.list_factors(
        status=status,
        sort_by="abs_icir",
        limit=composite_top_n,
        exclude_ids={"composite"},
    )

    # 2. Auto-resolve context from factors' context_id (merge all referenced).
    variables: dict[str, str] = {}
    parameters: dict[str, Any] = {}
    seen_ctx: set[str] = set()
    for f in factors:
        if f.context_id and f.context_id not in seen_ctx:
            seen_ctx.add(f.context_id)
            ctx = repo.get_context(f.context_id)
            if ctx is not None:
                variables.update(ctx.variables)
                parameters.update(ctx.parameters)

    # 3. Compute weights.
    weights = _compute_weights(factors, composite_method)

    # 4. Build composite expression.
    composite_expr = _build_composite_expression(weights, composite_transform)

    # 5. Assemble YAML structure.
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    doc: dict[str, Any] = {}

    ctx_label = "_".join(sorted(seen_ctx)) if seen_ctx else "registry"
    doc["metadata"] = {
        "name": f"registry_export_{ctx_label}",
        "version": "1.0.0",
        "description": (
            f"Auto-generated from registry ({len(factors)} {status} factors, "
            f"method={composite_method}, transform={composite_transform})"
        ),
    }

    if parameters:
        doc["parameters"] = parameters
    if variables:
        doc["variables"] = variables

    factors_section: dict[str, dict[str, str]] = {}
    for f in factors:
        entry: dict[str, str] = {"expression": f.expression}
        if f.description:
            entry["description"] = f.description
        if f.category:
            entry["category"] = f.category
        factors_section[f.factor_id] = entry

    factors_section["composite"] = {
        "expression": composite_expr,
        "description": (
            f"Auto-composite: {composite_method}, "
            f"{len(factors)} factors, transform={composite_transform}"
        ),
    }
    doc["factors"] = factors_section

    # 6. Write YAML.
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        f"# Auto-generated by alpha export-factors\n"
        f"# method: {composite_method}, top: {composite_top_n}, "
        f"transform: {composite_transform}\n"
        f"# generated: {now}\n\n"
    )

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(header)
        yaml.dump(doc, fh, default_flow_style=False, allow_unicode=True, sort_keys=False)

    return output_path


def _compute_weights(
    factors: list[FactorRecord],
    method: str,
) -> list[tuple[str, float]]:
    """Compute factor weights as (factor_id, weight) pairs.

    Returns an empty list if no factors are provided.
    """
    if not factors:
        return []

    if method == "icir_weight":
        # Use absolute ICIR; fall back to equal if no ICIR values.
        icir_values = [(f.factor_id, abs(f.icir)) for f in factors if f.icir is not None]
        if icir_values:
            total = sum(v for _, v in icir_values)
            if total > 0:
                return [(fid, v / total) for fid, v in icir_values]

    # Default: equal weight.
    n = len(factors)
    w = 1.0 / n
    return [(f.factor_id, w) for f in factors]


def _build_composite_expression(
    weights: list[tuple[str, float]],
    transform: str,
) -> str:
    """Build a DSL expression from weights and transform."""
    if not weights:
        return "0"

    terms: list[str] = []
    for factor_id, weight in weights:
        if transform == "raw":
            term = f"{weight:.4f} * {factor_id}"
        else:
            term = f"{weight:.4f} * {transform}({factor_id})"
        terms.append(term)

    return "\n+ ".join(terms)
